/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#82db7e",
        "on-primary": "#002c71",
        primary: "#b1c5ff",
        "surface-container": "#112036",
        "inverse-primary": "#345baf",
        "surface-container-low": "#0d1c32",
        "on-primary-container": "#8dadff",
        "on-secondary": "#1e304f",
        background: "#041329",
        "on-secondary-container": "#a3b5db",
        "on-error": "#690005",
        "surface-container-lowest": "#010e24",
        "tertiary-fixed": "#9df898",
        "surface-bright": "#2c3951",
        "on-tertiary": "#00390a",
        "secondary-container": "#354767",
        "surface-container-high": "#1c2a41",
        "secondary-fixed-dim": "#b5c7ed",
        "surface-variant": "#27354c",
        "on-surface-variant": "#c4c6d3",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#354767",
        "on-primary-fixed-variant": "#144296",
        "surface-tint": "#b1c5ff",
        "outline-variant": "#434652",
        "primary-container": "#0b3d91",
        "primary-fixed": "#dae2ff",
        "surface-dim": "#041329",
        "on-error-container": "#ffdad6",
        secondary: "#b5c7ed",
        outline: "#8e909d",
        "inverse-on-surface": "#233148",
        "primary-fixed-dim": "#b1c5ff",
        "on-tertiary-fixed": "#002204",
        "tertiary-container": "#004e11",
        "on-surface": "#d6e3ff",
        "on-tertiary-container": "#6bc269",
        "on-secondary-fixed": "#061b39",
        "secondary-fixed": "#d7e3ff",
        "on-tertiary-fixed-variant": "#005312",
        "on-background": "#d6e3ff",
        "surface-container-highest": "#27354c",
        "tertiary-fixed-dim": "#82db7e",
        "inverse-surface": "#d6e3ff",
        surface: "#041329",
        "on-primary-fixed": "#001947",
        error: "#ffb4ab",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      animation: {
        scan: "scan 3s linear infinite",
      },
      keyframes: {
        scan: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
      },
    },
  },
  plugins: [],
};
